# Generated by Django 4.1.3 on 2022-12-09 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(max_length=100)),
                ('song', models.CharField(max_length=100)),
                ('duration', models.FloatField()),
                ('gender', models.CharField(max_length=50)),
                ('listen', models.CharField(max_length=300)),
            ],
        ),
    ]
