# Generated by Django 4.1.7 on 2023-03-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0004_song_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='gender',
            field=models.CharField(choices=[('RAP', 'rap'), ('ROCK', 'rock'), ('REGAETTON', 'regaeton'), ('REGGUE', 'reggue'), ('BALADAS', 'baladas'), ('SALSA', 'salsa'), ('SALSA-CHOKE', 'salsa-choke'), ('BACHATA', 'bachata')], default='RAP', max_length=50),
        ),
    ]
