# Generated by Django 4.1.3 on 2023-05-18 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicApp', '0009_remove_comment_song_song_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='comments',
        ),
        migrations.AddField(
            model_name='comment',
            name='song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song_n', to='musicApp.song'),
        ),
    ]
